#!/bin/bash

# bashrc

[ -n "$PS1" ] && source ~/.bash_profile

# --- Network Check Start ---
if [[ $- == *i* ]]; then
    # Get the exact process name (e.g., "-zsh" or "bash")
    MY_PROC_NAME=$(ps -p $$ -o comm=)

    # We use '-e' to safely handle names starting with a dash (like -zsh)
    SHELL_COUNT=$(ps -A -o comm= | grep -cFx -e "$MY_PROC_NAME")

    if [ "$SHELL_COUNT" -eq 2 ]; then
        if [[ "$(uname)" == "Darwin" ]]; then
            ping  --apple-time 1.1.1.1
        elif [[ "$(uname)" == "Linux" ]]; then
            ping 1 1.1.1.1
        fi
    fi
fi
# --- Network Check End ---