#!/bin/bash

run_help() {

cat <<EOT
My dotfiles - Michael Kehoe - http://michael-kehoe.io.com/

Usage: $(basename "$0") [options]

Options:
    -h, --help      Print this help text
    -l, --list      Print a list of additional software to install
    --no-packages   Suppress package updates
    --no-sync       Suppress pulling from the remote repository

EOT

}